### ISSUE TITLE
Ocropus image no longer published on Docker Hub

### ISSUE THREAD

**Issue by tfmorris** [tmbarchive/docker-ocropus#2]
The current readme assumes that the image is published, but it isn't currently.  Additionally the path for ocropus on the built image is slightly wrong.

The following command will build a local docker image of ocropus:

```
docker build -t ocropus github.com/tmbdev/docker-ocropus
```

and the current run command for this local image is:

```
docker run -v `pwd`:/work ocropus /ocropy/ocropus-rpred *.png
```

**Comment by wanghaisheng** [comment]
```
[wanghs@db2 docker-ocropus-edwin]$ docker run -v `pwd`:/work edwin/ocropus /ocropy/ocropus-rpred *.png
INFO:
INFO:  ########## /ocropy/ocropus-rpred test.png
INFO:
Traceback (most recent call last):
  File "/ocropy/ocropus-rpred", line 98, in <module>
    inputs = ocrolib.glob_all(args.files)
  File "/ocropy/ocrolib/toplevel.py", line 213, in argument_checks
    result = f(*args,**kw)
  File "/ocropy/ocrolib/common.py", line 654, in glob_all
    raise FileNotFound("%s: expansion did not yield any files"%arg)
ocrolib.common.FileNotFound: file not found test.png: expansion did not yield any files

```

**Comment by kba** [comment]
@wanghaisheng You are mounting the current working dir to `/work`. Are you sure the PNG files are in there?

**Comment by wanghaisheng** [comment]
@kba  yeah 

```
[wanghs@db2 docker-ocropus-edwin]$ ls -al
总用量 3676
drwxrwxr-x 3 wanghs wanghs    4096 4月  19 11:48 .
drwxrwxr-x 4 wanghs wanghs    4096 4月  14 16:50 ..
-rw-rw-r-- 1 wanghs wanghs     733 4月  19 11:29 Dockerfile
-rw-rw-r-- 1 wanghs wanghs 3724865 4月  19 12:07 docker-machine
drwxrwxr-x 8 wanghs wanghs    4096 4月  14 16:48 .git
-rwxrwxr-x 1 wanghs wanghs     349 4月  14 16:48 ocrotrain.sh
-rw-rw-r-- 1 wanghs wanghs     481 4月  14 16:54 README.md
-rwxrwxr-x 1 wanghs wanghs      86 4月  14 16:48 run-ocropus
-rw-rw-r-- 1 wanghs wanghs    4538 4月  14 16:48 test.png
[wanghs@db2 docker-ocropus-edwin]$  docker run -v `pwd`:/work edwin/ocropus /ocropy/ocropus-rpred *.png
INFO:
INFO:  ########## /ocropy/ocropus-rpred test.png
INFO:
Traceback (most recent call last):
  File "/ocropy/ocropus-rpred", line 98, in <module>
    inputs = ocrolib.glob_all(args.files)
  File "/ocropy/ocrolib/toplevel.py", line 213, in argument_checks
    result = f(*args,**kw)
  File "/ocropy/ocrolib/common.py", line 654, in glob_all
    raise FileNotFound("%s: expansion did not yield any files"%arg)
ocrolib.common.FileNotFound: file not found test.png: expansion did not yield any files

```

**Comment by kba** [comment]
I maintain an up-to-date fork at https://github.com/kba/docker-ocropy, it's available from Dockerhub at https://hub.docker.com/r/kbai/ocropy/.

You can run

```sh
docker run -v `pwd`:/work kbai/ocropus /ocropy/ocropus-rpred *.png
```

or use the shell script:

```sh
./run-ocropy rpred *.png
```
